name: linting, testing, building
run-name: ${{ github.actor }} начал запуск тестирования сборки 🚀🚀🚀
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Устанавливаю модули
        run: npm install

      - name: Собираю проект в продакшн сборке
        run: npm run build

      - name: Запускаю linting
        run: npm run lint:ts

      - name: Запускаю linting scss
        run: npm run lint:scss

      - name: Запускаю unit тесты
        run: npm run test:unit
