name: linting, testing, building
run-name: ${{ github.actor }} начал запуск тестирования сборки 🚀🚀🚀
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Устанавливаю модули
        run: npm install

      - name: Собираю проект в продакшн сборке
        run: npm run build
        if: always()

      - name: Запускаю linting
        run: npm run lint:ts
        if: always()

      - name: Запускаю linting scss
        run: npm run lint:scss
        if: always()

      - name: Запускаю unit тесты
        run: npm run test:unit
        if: always()

      - name: Запускаю build-storybook
        run: npm run build-storybook
        if: always()

      - name: Запускаю test:ui:ci тесты
        run: npm run test:ui:ci
        if: always()
